; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = mega2560

; Set/override default options for each "[env:***]"
[env]
build_flags =
    -D VERSION=1.2.3
    -D DEBUG=1


[env:mega2560]
platform = atmelavr
framework = arduino
board = megaatmega2560
monitor_speed = 115200
lib_deps =
    Wire
    LiquidCrystal_I2c
    # marcoschwartz/LiquidCrystal_I2C
    Console=symlink://../../libs/Console
    # LCD=symlink://../../libs/LCD

    adafruit/Adafruit LED Backpack Library
    Multi7Seg=symlink://../../libs/Multi7Seg

    adafruit/RTClib
    PaulStoffregen/Time
    jchristensen/Timezone
    Clock=symlink://../../libs/Clock
lib_ldf_mode = deep+
lib_extra_dirs = ../../libs
;[env:native]
;platform = native
;test_framework = unity
