; PlatformIO Project Configuration File

[platformio]
src_dir = src
default_envs = eink47
extra_configs = platformio.local.ini

[env]
platform = espressif32
framework = arduino
upload_protocol = esptool
upload_speed = 921600
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps =
    Wire
    bblanchon/ArduinoJson@^7.0.4
    TxtingStatus=symlink://../../libs/TxtingStatus
build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3
    '-DWIFI_SSID="${sysenv.WIFI_SSID}"'
    '-DWIFI_PASSWORD="${sysenv.WIFI_PASSWORD}"'
    '-DSTATUS_URL="http://txtin.gs/status"'

[env:eink47]
board = esp32dev
board_build.mcu = esp32
board_build.f_cpu = 240000000L
platform_packages =
    framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#2.0.3
lib_deps =
    ${env.lib_deps}
    xinyuan-lilygo/LilyGoEPD47@^0.3.0
build_flags =
    ${env.build_flags}

[env:eink47-local]
extends = env:eink47
build_flags =
    ${env:eink47.build_flags}
    ; Example:
    ; '-DWIFI_SSID="${sysenv.WIFI_SSID}"'
    ; '-DWIFI_PASSWORD="${sysenv.WIFI_PASSWORD}"'
