[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

; change microcontroller
board_build.mcu = esp32s3

; change MCU frequency
; board_build.f_cpu = 240000000L

; Enable PSRAM (needed for high resolutions like UXGA)
board_build.arduino_psram = enabled

; Serial monitor settings
monitor_speed = 115200

; Use latest stable ESP32 Arduino core
platform_packages =
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git

; Pass Wi-Fi credentials from environment variables
build_flags =
    -DWIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -DWIFI_PASS=\"${sysenv.WIFI_PASS}\"

; Optional: Optimize for PSRAM use
build_unflags = -Os
build_flags =
    -O2
    -mfix-esp32-psram-cache-issue

[env:esp-eye]
platform = espressif32
board = esp32-evb
framework = arduino

; Enable PSRAM (needed for high resolutions like UXGA)
board_build.arduino_psram = enabled

; Serial monitor settings
monitor_speed = 115200

; Use latest stable ESP32 Arduino core
platform_packages =
    framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git

; Pass Wi-Fi credentials from environment variables
build_flags =
    -DWIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -DWIFI_PASS=\"${sysenv.WIFI_PASS}\"

; Optional: Optimize for PSRAM use
build_unflags = -Os
build_flags =
    -O2
    -mfix-esp32-psram-cache-issue
